#!/usr/bin/env python3
"""Asserts that every verbatim copy block from the incumbent page is present in index.html."""
import html, re, sys, pathlib
SENTINELS = [
    # extended by Task 3 and Task 4 — each entry is the exact visible text of a block
    'Help launch Deckhand. Keep three months of Elite.',
    "Deckhand turns your phone into a Stream-Deck-style control surface for Windows, macOS and Linux — no extra hardware, no account, no cloud. It's finished. What it needs now is twelve people willing to use it daily for fourteen days, so Google Play will let it out.",
    'Deckhand is in closed testing',
    "Three steps and you're live.",
    'No setup wizard, no cloud account, no hardware to buy.',
    'Install the free desktop app, then scan the QR code it shows (or type the on-screen PIN) from your phone. Both devices just need to share a network.',
    'Drag tiles onto a grid across as many pages as your plan allows. Resize them, skin them, wire each one to whatever it should do.',
    'Fire hotkeys, macros, OBS scenes, media controls, or a webhook to anything with a URL — straight from your pocket.',
    'Way more than buttons.',
    'Fourteen control types in total — buttons, dials, faders, toggles, radial menus, text fields, gauges, color pickers, steppers, multi-state switches, XY pads, joysticks, D-pads, and sparklines.',
    "Things a hardware Stream Deck can't do.",
    'OBS Studio scene, stream, and recording control. HTTP webhooks that trigger smart-home devices, APIs, or anything with a URL. Shake-to-trigger, voice-activated tiles, and geofenced pages that switch automatically when you sit down at your desk.',
    'A macro recorder captures a sequence of your own tiles and replays it as one',
    'Shell commands and system power actions — opt-in only, never on by default',
    'Skin every tile, every page.',
    'End-to-end encrypted local pairing',
    'Made for your setup.',
    "The same deck engine, skinned differently for whatever you're actually doing.",
    'Twelve testers.',
    'Fourteen days.',
    'Then Deckhand can launch.',
    "Google Play doesn't let a new developer publish anything until at least twelve people have run the app in a closed test for fourteen days in a row.",
    'Open the app once a day, for fourteen days.',
    "Work through the day's quests.",
    'Say what broke.',
    'Three months of Elite, free, when Deckhand launches.',
    'Every paid feature unlocked from day one.',
    'No ads. None.',
    'A say in what ships.',
    'Bring a tester, add a month.',
    'Every tester goes past me first.',
    'The month lands when they do.',
    'No cap, and it all stacks.',
    'And the reason to do it this week rather than next:',
    'Refer someone now',
    "The fourteen days, and what they're worth",
    'Perfect attendance',
    'You get quests, not homework.',
    'Wheel of fortune',
    'Hold the line',
    'Full range',
    'An Android phone or tablet.',
    'Play auto-update left on.',
    'Join the test',
    'Email us to become a tester',
    'Straight answers before you commit',
    'Is my usage tracked during the test?',
    "Why can't I take a screenshot?",
    'What happens if I miss a day?',
    'When exactly do I get the three months of Elite?',
    'How does the extra month for referring work?',
    'Can I quit partway through?',
    'Does it cost anything?',
    "Start free. Your deck grows when you're ready.",
    'Free tier is real functionality, not a trial',
    'Starter and Creator are monthly only; Studio and up bill monthly or yearly (yearly ≈ 2 months free).',
    'Tile cells / page',
    'Banner + 2-min rewarded',
    'These are launch prices.',
    "Skins are always a separate one-time purchase at every tier, including Free, and are never bundled into a subscription — buy a skin once and it's yours for good. 2 skins are free built-ins; 48 more range $0.99–$69.99.",
    'Get Deckhand.',
    'Coming soon',
    'Apple Silicon',
    'After the download — one step per platform',
    'Windows will show',
    'This build is from 24 August',
    'xattr -d com.apple.quarantine Deckhand-Installer-macos-arm64',
    '--appimage-extract-and-run',
    'One installer, no admin/root needed',
    'Your pocket-sized command deck. A Stream-Deck-style control surface for Windows, macOS, and Linux — built by Day Dream Corp.',
    '"Stream Deck" is a trademark of Elgato — Deckhand is an independent product, not affiliated with or endorsed by Elgato.',
    '© 2026 Day Dream Corp. All rights reserved.',
]
src = pathlib.Path("index.html").read_text(encoding="utf-8")
text = re.sub(r"<[^>]+>", " ", src)
text = html.unescape(text)
text = re.sub(r"\s+", " ", text)
missing = [s for s in SENTINELS if re.sub(r"\s+", " ", html.unescape(s)) not in text]
for m in missing: print("MISSING:", m[:80])
print(f"check_copy: {len(SENTINELS)-len(missing)}/{len(SENTINELS)} present")
sys.exit(1 if missing else 0)
