#!/usr/bin/env bash
# Fetches the pinned third-party files into a scratch dir and copies only what the site serves.
# Also regenerates assets/js/deck/presets.js from the app repo's preset deck files (same machine only).
set -euo pipefail
SITE="$(cd "$(dirname "$0")/.." && pwd)"
APP_DECKS="${APP_DECKS:-/home/thisfuck/Code/Mobile/deckhand/marketing/decks}"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
cd "$SCRATCH"
npm init -y >/dev/null
npm install --no-audit --no-fund --silent gsap@3.15.0 @material-design-icons/svg@0.14.15
test -d node_modules/@material-design-icons/svg/filled || { echo "no filled/ dir in @material-design-icons/svg" >&2; exit 1; }
mkdir -p "$SITE/assets/vendor/gsap" "$SITE/assets/icons" "$SITE/assets/js/deck"
for f in gsap ScrollTrigger SplitText Flip DrawSVGPlugin; do
  cp "node_modules/gsap/dist/$f.min.js" "$SITE/assets/vendor/gsap/$f.min.js"
done
if ls node_modules/gsap/LICENSE* >/dev/null 2>&1; then cp node_modules/gsap/LICENSE* "$SITE/assets/vendor/gsap/LICENSE.txt"; else cp node_modules/gsap/README.md "$SITE/assets/vendor/gsap/LICENSE.txt"; fi
cp node_modules/@material-design-icons/svg/LICENSE "$SITE/assets/icons/LICENSE.txt"
ICONS="bolt keyboard text_fields launch link folder play_arrow mic http power_settings_new star home settings volume_up terminal devices wifi palette workspace_premium edit expand_less check add remove lock"
{
  echo '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'
  for i in $ICONS; do
    f="node_modules/@material-design-icons/svg/filled/$i.svg"
    test -f "$f" || { echo "missing icon $i" >&2; exit 1; }
    inner="$(sed -e 's/<svg[^>]*>//' -e 's#</svg>##' "$f" | tr -d '\n')"
    echo "<symbol id=\"$i\" viewBox=\"0 0 24 24\">$inner</symbol>"
  done
  echo '</svg>'
} > "$SITE/assets/icons/sprite.svg"
if [ -d "$APP_DECKS" ]; then
  python3 - "$APP_DECKS" "$SITE/assets/js/deck/presets.js" <<'PY'
import json, sys, pathlib
src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
files = {"obs": "deck_english.json", "dj": "deck_dj_booth.json", "home": "deck_smart_home.json",
         "kitchen": "deck_kitchen.json", "classroom": "deck_classroom.json", "photo": "deck_photo_studio.json"}
docs = {k: json.loads((src / v).read_text(encoding="utf-8")) for k, v in files.items()}
for k, d in docs.items():
    assert d["schemaVersion"] == 2 and len(d["pages"][0]["slots"]) == 10, k
body = json.dumps(docs, ensure_ascii=False, indent=1)
out.write_text("// GENERATED by scripts/vendor.sh from deckhand/marketing/decks — do not edit by hand.\n"
               "export const PRESETS = " + body + ";\n", encoding="utf-8")
print("presets:", ", ".join(f"{k}={d['pages'][0]['name']}" for k, d in docs.items()))
PY
else
  echo "APP_DECKS not found ($APP_DECKS); presets.js left as is" >&2
fi
echo "vendored: $(ls "$SITE/assets/vendor/gsap" | tr '\n' ' ')"
echo "icons: $(grep -c '<symbol' "$SITE/assets/icons/sprite.svg")"
